shoplist = ['apple', 'mango', 'carrot', 'banana', 'xbox']
name = 'sherlock'

print('Item 0 is:', shoplist[0])
print('Item 1 is:', shoplist[1])
print('Item 2 is:', shoplist[2])
print('Item 3 is:', shoplist[3])
print('Item 4 is:', shoplist[4])
print('Item -1 is:', shoplist[-1])
print('Item -2 is:', shoplist[-2])
print('Character 0 is:', name[0])

print('Item 1 to 3 are', shoplist[1:3])
print('Item 1 to 4 are', shoplist[1:4])
print('Item 2 to end are', shoplist[2:])
print('Item 1 to -1 are', shoplist[1:-1])
print('Item 1 to -2 are', shoplist[1:-2])
print('Item 1 to -3 are', shoplist[1:-3])
print('Item 1 to -4 are', shoplist[1:-4])
print('Item star to end are', shoplist)
print(shoplist[::1])
print(shoplist[::2])
print(shoplist[::-1])
print(shoplist[::-2])
print('Character 1 to 3 is', name[1:3])
print('Character 1 to 3 is', name[1:3])
print('Character 2 to end is', name[2:])
print('Character 1 to -1 is', name[1:-1])
print('Character star to end is', name[:])

